package lib.minecraft.text.font;

import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;

/**
 * Loads the committed synthetic colour-font fixtures ({@code src/test/resources/colorfont}) that
 * back the colour-glyph test suite. Every fixture is generated by the {@code gen_fixtures.py}
 * pipeline from synthetic cells - no real pack assets.
 * <p>
 * The colour output is a single merged {@code SynthColour.ttf} carrying both font ids. Stored
 * codepoints are allocated over the raster pairs sorted by {@code (font_id, original_codepoint)},
 * so {@code synth:alt} (which sorts first) takes gid 1 and {@code synth:demo}'s glyphs follow at
 * gids 2..6. {@link #demoFont()} and {@link #altFont()} both load that one file.
 */
final class ColorFontFixtures {

    static final @NotNull FontId DEMO = FontId.parse("synth:demo");
    static final @NotNull FontId ALT = FontId.parse("synth:alt");

    /** The single merged colour font backing every font id. */
    static final @NotNull String MERGED_TTF = "SynthColour.ttf";

    /** Total glyph count in the merged font: .notdef + alt E001 + demo's five distinct glyphs. */
    static final int NUM_GLYPHS = 7;

    // gids in the merged glyph order (see the sidecar): alt first, then demo's glyphs
    static final int GID_ALT_FLAT = 1;    // alt E001, 8x8 green/yellow
    static final int GID_FLAT = 2;        // demo E001, 8x8 red/blue (also CP_FLAT_DUP)
    static final int GID_AA = 3;          // demo E002, 8x8 anti-aliased multi-colour
    static final int GID_MID = 4;         // demo E004, 16x16, strike ppem 8
    static final int GID_DOWNSCALED = 5;  // demo E005, 16x16, strike ppem 16
    static final int GID_TALL = 6;        // demo E006, 256x256

    // demo raster glyphs
    static final int CP_FLAT = 0xE001;       // gid 2, strike ppem 8, 8x8 red/blue (fully opaque)
    static final int CP_AA = 0xE002;         // gid 3, strike ppem 8, 8x8 anti-aliased multi-colour
    static final int CP_FLAT_DUP = 0xE003;   // gid 2 (dedup of CP_FLAT)
    static final int CP_MID = 0xE004;        // gid 4, strike ppem 8, 16x16
    static final int CP_DOWNSCALED = 0xE005; // gid 5, strike ppem 16, 16x16
    static final int CP_TALL = 0xE006;       // gid 6, strike ppem 8, 256x256
    // demo space glyphs
    static final int CP_NEG_SPACE = 0xE010;  // advance -1024 units = -16 output px
    static final int CP_FRAC_SPACE = 0xE011; // advance 96 units = 1.5 output px

    private ColorFontFixtures() {}

    static byte[] bytes(@NotNull String name) {
        try (InputStream in = ColorFontFixtures.class.getClassLoader().getResourceAsStream("colorfont/" + name)) {
            if (in == null) throw new IllegalStateException("Missing colour-font fixture: colorfont/" + name);
            return in.readAllBytes();
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }

    static @NotNull Reader sidecarReader() {
        InputStream in = ColorFontFixtures.class.getClassLoader().getResourceAsStream("colorfont/Minecraft-Synth.colour-glyphs.json");
        if (in == null) throw new IllegalStateException("Missing colour sidecar fixture");
        return new InputStreamReader(in, StandardCharsets.UTF_8);
    }

    static @NotNull ColorGlyphSidecar sidecar() {
        try (Reader reader = sidecarReader()) {
            return ColorGlyphSidecar.parse(reader);
        } catch (IOException ex) {
            throw new UncheckedIOException(ex);
        }
    }

    static @NotNull SbixReader edgeReader() {
        return new SbixReader(bytes("SynthColour-edge.ttf"));
    }

    static @NotNull MinecraftFont.Color demoFont() {
        return MinecraftFont.Color.of(DEMO, bytes(MERGED_TTF), sidecar(), MinecraftFont.Vanilla.REGULAR);
    }

    static @NotNull MinecraftFont.Color altFont() {
        return MinecraftFont.Color.of(ALT, bytes(MERGED_TTF), sidecar(), MinecraftFont.Vanilla.REGULAR);
    }

}
